version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: dev
  - package-ecosystem: npm
    directory: "/packages/renderer"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: dev
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: dev
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: dev
